project = sigma_delta
vendor = xilinx
family = spartan6
part = xc6slx9-3tqg144
top_module = top_level

hdlfiles = ../vhdl/cic/cic.vhd ../vhdl/add_gen/address_generator.vhd ../vhdl/adc/adc.vhd ../vhdl/comb/comb.vhd ../vhdl/decimator/decimator.vhd ../vhdl/fir/fir.vhd ../vhdl/integrator/integrator.vhd ../vhdl/Packages/constantes.vhd ../vhdl/Packages/extra_functions.vhd ../vhdl/preadd_mac/preadd_mac.vhd ../vhdl/ram/ram.vhd ../vhdl/uart/Tx_uart.vhd ../vhdl/uart/Rx_uart.vhd ../vhdl/TOP_LEVEL/top_level.vhd  ../vhdl/pll/pll.vhd

include xilinx.mk
