project = adc
vendor = xilinx
family = spartan6
part = xc6slx9-3tqg144
top_module = adc

hdlfiles = ../vhdl/cic/cic.vhd ../vhdl/add_gen/address_generator.vhd ../vhdl/adc/adc.vhd ../vhdl/comb/comb.vhd ../vhdl/decimator/decimator.vhd ../vhdl/fir/fir.vhd ../vhdl/integrator/integrator.vhd ../vhdl/Packages/constantes.vhd ../vhdl/Packages/extra_functions.vhd ../vhdl/preadd_mac/preadd_mac.vhd ../vhdl/ram/ram.vhd

include xilinx.mk
